language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - doc # Just the package-list is needed for JavaDoc task; OK to fetch the latest version here.

    - extra-android-m2repository # Exact version specified in gradle.properties; OK to fetch latest version here.

    - android-22
    - sys-img-armeabi-v7a-android-22
    - android-24
  licenses:
    - 'android-sdk-license-.*'

env:
  matrix:
    - AVD_API_LEVEL=android-22


before_script:
  - echo no | android create avd --force -n test --target $AVD_API_LEVEL
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - sleep 30
  - adb shell input keyevent 82 &

script:
  - adb logcat > logcat.txt & # write logs to a file, to make test failure debugging easier
  - TERM=dumb ./gradlew -PIS_PREDEXING_ENABLED=false assemble connectedCheck lint findbugs releaseJavadoc --stacktrace

after_failure:
  - cat logcat.txt
